### ISSUE TITLE
Consider making ActiveBackground a wrapper instead of an insert

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/react-active-background#3]
Right now a consumer is required to:

- `import` the css
- ensure the wrapper is `relative`
- ensure that `ActiveBackground` is the first child.

Consider exposing a second, or replacing the current, with a self-wrapping component:

```tsx
<ActiveBackground pattern={Confetti}>
  ...
</ActiveBackground>
```

**Comment by neenjaw** [comment]
Done, wonderful suggestion
