### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by iHiD** [exercism/react-active-background#6]
Please add a licence. Preferably AGPL3 but I'd be on with MIT too.

**Comment by neenjaw** [comment]
I'd like to add MIT to it I think

**Comment by neenjaw** [comment]
added and closed

**Comment by iHiD** [comment]
Cool. What's the reason you prefer MIT over AGPL (just so I understand)?

**Comment by neenjaw** [comment]
I think the biggest reason I would say is that it's a very small piece of code, and the original confetti animation is a derivation from other work.

**Comment by iHiD** [comment]
Cool. Makes sense. Thanks 🙂
